import "@/app/styles/styles.css";
import "@/app/styles/globals.css";
import NextTopLoader from "nextjs-toploader";
import { sfPro } from "../styles/fonts";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader color="#8BA70D" showSpinner={false} height={4} />
        {children}
      </body>
    </html>
  );
}
