export const routes = {
  changepassword: "/change-password",
  admin: "/admin/dashboard",
  clubmanagement: "/admin/club-management",
  totalclubs: "/admin/club-management/total-clubs",
  clubRequest: "/admin/club-management/club-requests",
  clubWallet: "/admin/club-management/club-wallet",
  usermanagement: "/admin/user-management",
  addnewuser: "/admin/user-management/add-newuser",
  userdetails: "/admin/user-management/user-details",
  chatRoom: "/admin/chat-room",
  bookingmanagement: "/admin/booking-management",
  matches: "/admin/booking-management/matches",
  transections: "/admin/booking-management/transactions",
  discount: "/admin/discount",
  financialRevenuReport: "/admin/financial-management",
  incomeAndSpendingLogs: "/admin/financial-management/income-and-spending-logs",
  TreasuryManagement: "/admin/financial-management/treasury-management",
  DuePayment: "/admin/financial-management/due-payment",
  securityIncidents: "/admin/security-incidents",
  auditLogs: "/admin/security-incidents/audit-logs",
  systemErrorsLogs: "/admin/security-incidents/system-error-logs",
  marketingNotification: "/admin/marketing-notification",
  supportAndFeedback: "/admin/feedback",
  applicationConfiguration: "/admin/application-configuration",
  clubConfiguration: "/admin/application-configuration/club-configuration",
};
